version: '3.5'

services:
  postgres:
    container_name: test_postgres
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: space_flight_articles_test
      PGDATA: /data/postgres
    volumes:
       - "./../setup-database.sql:/docker-entrypoint-initdb.d/1-setup-database.sql"
    ports:
      - "5433:5432"
    restart: unless-stopped
